# Use Node base image
FROM node:20 AS vizrep 

# echo "Building the Docker image..."
RUN echo "Building the Docker image..."

# Create necessary directories with proper permissions
RUN mkdir -p /usr/src/app/shared/mmar/mmar-vizrep-client \
    /usr/src/app/shared/mmar/mmar-global-data-structure  

    # Copy the start-vizrep-client.sh script into the container
COPY scripts/start-vizrep-client.sh /usr/src/app/start-vizrep-client.sh
# Set permissions for the script
RUN chmod +x /usr/src/app/start-vizrep-client.sh

# Copy the npm-installation-vizrep-client.sh script into the container
COPY scripts/npm-installation-vizrep-client.sh /usr/src/app/npm-installation-vizrep-client.sh
# Set permissions for the script
RUN chmod +x /usr/src/app/npm-installation-vizrep-client.sh

# Copy start-node-vizrep-client.sh script into the container
COPY scripts/start-node-vizrep-client.sh /usr/src/app/start-node-vizrep-client.sh
# Set permissions for the script
RUN chmod +x /usr/src/app/start-node-vizrep-client.sh

#COPY all the files from conf to /usr/src/app/mmar-config-files -> environment files for node projects
COPY conf /usr/src/app/mmar-config-files

RUN echo "Running the start-vizrep-client.sh script for mmar-server..."
# Run the start-vizrep-client.sh script
CMD [ "/usr/src/app/start-vizrep-client.sh"]